### ISSUE TITLE
KeyError: 'lattice_vectors' show up when I run command casm calc -setup

### ISSUE THREAD

**Issue by q654262498** [prisms-center/CASMcode#225]
Calculation directory: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
JobID: []
Constructing a VASP Relax object
  Calculation directory: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
VASP Relax object constructed

Preparing to submit a VASP relaxation PBS job
Setting up VASP input files: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/SCEL1_1_1_1_0_0_0/0/calctype.default
  Reading reference KPOINTS: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/settings/calctype.default/KPOINTS
  Reading reference POSCAR: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/settings/calctype.default/POSCAR
  Reading SPECIES: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/settings/calctype.default/SPECIES
  Reading structure: /home/c903/software/casmjob/LYJ/MgCajob1/training_data/SCEL1_1_1_1_0_0_0/0/structure.json
Traceback (most recent call last):
  File "/home/c903/software/anaconda3/envs/casm/bin/casm", line 8, in <module>
    sys.exit(main())
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/scripts/casm.py", line 99, in main
    python_commands[args.command](argv[1:])
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/scripts/casm_calc.py", line 130, in main
    raise e
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/scripts/casm_calc.py", line 121, in main
    calculator.submit()
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vaspwrapper/relax.py", line 118, in submit
    super(Relax, self).submit()
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vaspwrapper/vasp_calculator_base.py", line 391, in submit
    self.config_setup(config_data)
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vaspwrapper/relax.py", line 107, in config_setup
    super(Relax, self).config_setup(config_data)
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vaspwrapper/vasp_calculator_base.py", line 153, in config_setup
    vasp.io.write_vasp_input(config_data["calcdir"], incarfile,
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vasp/io/io.py", line 187, in write_vasp_input
    structure = poscar.Poscar(structurefile, species_settings)
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vasp/io/poscar.py", line 72, in __init__
    self.read_structure_json(filename, species)
  File "/home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vasp/io/poscar.py", line 130, in read_structure_json
    self._lattice = np.array(config_data['lattice_vectors'])
KeyError: 'lattice_vectors'

I put the correct input file in the specified folder,but I still got this error,how can I deal with it?

**Comment by NotThatGreatAtLife** [comment]
I got this error, I fixed it by editing line 130 in /home/c903/software/anaconda3/envs/casm/lib/python3.10/site-packages/casm/vasp/io/poscar.py to be 'lattice' instead of 'lattice_vectors'. That at least allowed the jobs to run without error, the error comes about again when doing the "casm -update" command though, which I am trying to figure out how to deal with now...

**Comment by bpuchala** [comment]
Please see #226 also, this may be an issue with conflicting versions of CASM installed.
