### ISSUE TITLE
Nersc slurm submit job error

### ISSUE THREAD

**Issue by jhung12** [prisms-center/CASMcode#238]
I am running casm on nersc.

> sbatch: error: No architecture specified, cannot estimate job costs.
> sbatch: error: Batch job submission failed: Unspecified error
> Traceback (most recent call last):
>   File "/global/homes/j/jhung/.conda/envs/casm/bin/casm-calc", line 8, in <module>
>     sys.exit(main())
>   File "/global/homes/j/jhung/.conda/envs/casm/lib/python3.9/site-packages/casm/scripts/casm_calc.py", line 130, in main
>     raise e
>   File "/global/homes/j/jhung/.conda/envs/casm/lib/python3.9/site-packages/casm/scripts/casm_calc.py", line 121, in main
>     calculator.submit()
>   File "/global/homes/j/jhung/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/relax.py", line 118, in submit
>     super(Relax, self).submit()
>   File "/global/homes/j/jhung/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/vasp_calculator_base.py", line 430, in submit
>     job.submit()
>   File "/global/homes/j/jhung/.conda/envs/casm/lib/python3.9/site-packages/prisms_jobs/job.py", line 206, in submit
>     self.jobID = config.software().submit(substr=self.sub_string())
>   File "/global/homes/j/jhung/.conda/envs/casm/lib/python3.9/site-packages/prisms_jobs/interface/slurm.py", line 365, in submit
>     raise JobsError(0, "Submission error.\n" + stdout + "\n" + stderr)
> TypeError: can only concatenate str (not "NoneType") to str
> (casm) jhung@cori09:/global/cscratch1/sd/jhung/2H/CASM/training_data/settings/calctype.default> vim ../../SCEL6_6_1_1_0_5_5/61/calctype.default/SCEL6_6_1_1_0_5_5.61
> 

the sbatch error says that i did not specify the compute node.
But I did in my calc.json

> {
>   "queue":"batch",
>   "walltime":"48:00:00",
>   "ppn":"64",
>   "run_limit":9,
>   "final":"INCAR.final",
>   "nodes":6,
>   "software":"vasp",
>   "method":"relax",
>   "extra_input_files": ["vdw_kernel.bindat"],
>   "qos":"debug",
>   "constraint":"knl"
> }

So when I check the submit file, it does not show the constraint line

> #!/bin/sh
> #SBATCH -t 48:00:00
> #SBATCH -n 384
> #SBATCH --qos=debu
> #SBATCH -p batch
> python -c "import casm.vaspwrapper; obj = casm.vaspwrapper.Relax.from_configuration_dir('/global/cscratch1/sd/jhung/2H/CASM/training_data/SCEL6_6_1_1_0_5_5/61', 'default'); obj.run()"
> 

And also in the submit file, is it possible to add the feature that writes the amount of node and the amount the cores that i have asked for in the calc.json?

For exaple as above,
I have ppn =64, nodes =6.  total amount of cores = 384.
but i actually want 6 nodes with 64 cores each.
if using -n 384, I might get some nodes that do not using 64 cores.

the reason is that i have put NPAR in the INCAR file to accelarate the calculation. and the number i have set is best for #CORES=64

**Comment by bpuchala** [comment]
> So when I check the submit file, it does not show the constraint line

It's not clear to me why this is not showing up. 

> And also in the submit file, is it possible to add the feature that writes the amount of node and the amount the cores that i have asked for in the calc.json?

Currently the slurm interface does not allow this as an option. 


To check on why the constraint is not being included, and to customize the submit script that is generated, you could edit the code generating the submit string, which is created using the `prisms_jobs` python package [here](https://github.com/prisms-center/prisms_jobs/blob/039e9d7dc9852b784d87343151470992853afe82/prisms_jobs/interface/slurm.py#L94)

**Comment by jhung12** [comment]
i customize the submit script and it works

But there is another issue for job.queue,  
this must to specify in calc.json,or I will get an error from CASM. But NERSC did not like this line.
When using 

> #SBATCH -p batch 

I got error from NERSC
I have to delete it
