### ISSUE TITLE
Cannot check hull and pick eci

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#252]
Dear CASM developers,

After doing casm learn -s fit_1_ga.json, I got error check hull and pick eci. What causes this error?

casm learn -s fit_1_ga.json --checkhull --indiv 0
Loading fit_1_ga.json
Loading Hall of Fame: fit_1_ga_halloffame.pkl
# Get problem data...
# Reading existing problem specs from: fit_1_ga_specs.pkl
#   DONE

-- Check: individual 0  --
Index: Selected                                    #Selected    CV           RMS          wRMS         Estimator                FeatureSelection         Note
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
    0: 1011000010100001010001010000110110000100... 40           0.044531623  0.031555065  0.031555065  LinearRegression         GeneticAlgorithm         

Traceback (most recent call last):
  File "/global/homes/v/voz5005/.conda/envs/casm/bin/casm", line 8, in <module>
    sys.exit(main())
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/scripts/casm.py", line 99, in main
    python_commands[args.command](argv[1:])
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/scripts/casm_learn.py", line 162, in main
    casm.learn.fit.checkhull(input,
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/learn/fit.py", line 2127, in checkhull
    write_eci(proj,
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/project/io.py", line 61, in write_eci
    linear_orbit_index = function_keys[index][0]
KeyError: 28

casm learn -s fit_1_ga.json --select 0
Loading fit_1_ga.json
Loading Hall of Fame: fit_1_ga_halloffame.pkl
Traceback (most recent call last):
  File "/global/homes/v/voz5005/.conda/envs/casm/bin/casm", line 8, in <module>
    sys.exit(main())
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/scripts/casm.py", line 99, in main
    python_commands[args.command](argv[1:])
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/scripts/casm_learn.py", line 184, in main
    write_eci(proj,
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/project/io.py", line 61, in write_eci
    linear_orbit_index = function_keys[index][0]
KeyError: 28

**Comment by bpuchala** [comment]
Did you solve this? We have occasionally seen issues with installation of incompatible conda CASM packages and Python casm-python versions that might be related to this. Please check that you have the latest versions installed.

**Comment by sjtuzhanglei** [comment]
python --version
Python 3.9.13
casm --version
casm version: 1.2.0

**Comment by bpuchala** [comment]
The `casm-python` package should be at 1.2.1, you can check with `pip freeze`.

Another possibility is that if you re-generated the basis set with changes to bspecs.json and `casm bset -uf`, then the ECI sets in the hall of fame could be out-of-sync with the current basis set. If you've changed the basis set, you'll need to re-fit the eci.

**Comment by sjtuzhanglei** [comment]
pip freeze
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi-bindings_1649500321618/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1618968359944/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1640799537051/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
bash_kernel==0.7.2
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1649463573192/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1649361991009/work
bokeh==2.4.3
casm-python==1.2.1

It seems the version of cask-python is correct. The second probability might be the reason.
