### ISSUE TITLE
TypeError in running VASP.relax.report (CASM version 1.2.0)

### ISSUE THREAD

**Issue by arpitap112** [prisms-center/CASMcode#279]
Dear Developers,

I am a new user of CASM code. I have installed CASM code (version 1.2.0, https://prisms-center.github.io/CASMcode_docs/pages/installation/) in the local machine (Ubuntu 20.04) using the following steps:

1. Install anaconda3
1. conda create -n casm \
  --override-channels -c prisms-center -c conda-forge \
  casm-cpp=1.2.0 python=3
2. pip install casm-python 

The used python version is 3.9.15 and pip version is 22.3.1. 

I am following all the steps that the ZrO tutorial (https://prisms-center.github.io/CASMcode_docs/pages/tutorials/) mentions to build a cluster expansion Hamiltonian for binary alloy system. I have successfully generated all the structural configurations and VASP input files for each one using "casm calc --setup". Due to different submission criteria in my supercomputer, I had to use a different submission script to submit all the VASP calculations in the /training/SCEL*/CONFIG*/calctype.default/. Each folder contains all VASP input and output files including vasprun.xml.
I am getting the following error when I use vasp.relax.report command (going into the directory where VASP calculation is performed, vasp.relax.report ./) to create properties.calc.json file.

Begin vasp.relax.report
Unable to report properties for directory ./. Please verify that it contains a completed VASP calculation.
Traceback (most recent call last):
  File "/opt/apps/anaconda3/envs/casm/bin/vasp.relax.report", line 8, in <module>
    main()
  File "/opt/apps/anaconda3/envs/casm/lib/python3.9/site-packages/casm/scripts/vasp_relax_report.py", line 22, in main
    output = casm.vaspwrapper.Relax.properties(configdir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Relax.properties() missing 1 required positional argument: 'calcdir'

I would greatly appreciate any help to resolve this issue. 
Best,
Arpita

**Comment by seshasaibehara** [comment]
- There is a bug in `vasp_relax_report` which is causing this issue. A bug fix will be issued soon. 
- In the meantime, you can use `casm-calc --report` to get `properties.calc.json` for all the completed calculations.

**Comment by arpitap112** [comment]
Thank you very much for getting back. I will use cash-calc --report for now and will be on the lookout for the upcoming version.

**Comment by ghost** [comment]
Hi @seshasaibehara. I'm curious if you have corrected the issues with vasp_relax_report.

Additionally, I'm attempting to use casm import to import a structure along with all of its energetic properties. It seems that casm import —pos properties.calc.json does not work. Do you have the revised tutorial for this command ?

Thanks.

**Comment by darjaved** [comment]
Hi @seshasaibehara, could you please update, this issue has been resolved or not? and what is the alternate way?
