### ISSUE TITLE
Error after the static run

### ISSUE THREAD

**Issue by sjtuzhanglei** [prisms-center/CASMcode#330]
++  status: complete   next task: None
mv  run.final
Complete VASP job: /pscratch/sd/v/voz5005/RuO2/casm/211/srun64/casm/training_data/SCEL1_1_1_1_0_0_0/1/calctype.default/run.final
  rm: 
 gzip: 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/relax.py", line 122, in run
    super(Relax, self).run()
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/vasp_calculator_base.py", line 589, in run
    self.finalize(config_data)
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/relax.py", line 136, in finalize
    super(Relax, self).finalize(config_data)
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/vasp_calculator_base.py", line 657, in finalize
    output = self.properties(vaspdir, structurefile, speciesfile)
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/relax.py", line 141, in properties
    output = super(Relax, self).properties(calcdir, super_poscarfile,
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vaspwrapper/vasp_calculator_base.py", line 686, in properties
    unsort_dict = initial_structure.unsort_dict()
  File "/global/homes/v/voz5005/.conda/envs/casm/lib/python3.9/site-packages/casm/vasp/io/poscar.py", line 259, in unsort_dict
    basis_dict[atom] += range(start, end)
TypeError: unsupported operand type(s) for +=: 'range' and 'range'
/pscratch/sd/v/voz5005/RuO2/casm/211/srun64/casm/training_data/SCEL1_1_1_1_0_0_0/1/calctype.default/run.0/

**Comment by sjtuzhanglei** [comment]
Is it because my POSCAR is in selective dynamics mode?

**Comment by sjtuzhanglei** [comment]
I manually changed those artificial *_mobile/*_fixed atomic species to T T T/F F F.
