### ISSUE TITLE
numpy giving error since since the last CASM update

### ISSUE THREAD

**Issue by darjaved** [prisms-center/CASMcode#332]
Since the last CASM update with the python  version 3.9, i am facing the problem with the numpy during the weight optimization and error is as:

Traceback (most recent call last):
  File "/home/javeed/Desktop/CE/fit1/optimize_weight.py", line 95, in <module>
    res = gp_minimize(f, params, acq_func="EI", n_calls=500, n_random_starts=10, n_jobs=1, verbose=True) # n_calls is no of iterations of the BO process
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/optimizer/gp.py", line 259, in gp_minimize
    return base_minimize(
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/optimizer/base.py", line 298, in base_minimize
    next_x = optimizer.ask()
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 367, in ask
    return self._ask()
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/optimizer/optimizer.py", line 434, in _ask
    return self.space.rvs(random_state=self.rng)[0]
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/space/space.py", line 900, in rvs
    columns.append(dim.rvs(n_samples=n_samples, random_state=rng))
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/space/space.py", line 698, in rvs
    return self.inverse_transform(list(choices))
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/space/space.py", line 685, in inverse_transform
    inv_transform = super(Categorical, self).inverse_transform(Xt)
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/space/space.py", line 168, in inverse_transform
    return self.transformer.inverse_transform(Xt)
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/space/transformers.py", line 309, in inverse_transform
    X = transformer.inverse_transform(X)
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/skopt/space/transformers.py", line 275, in inverse_transform
    return np.round(X_orig).astype(np.int)
  File "/home/javeed/anaconda3/envs/casm/lib/python3.9/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

this issue was not with the python version 3.6. 

what can be the possible solution? i tried to install the casm with the python 3.6, but its giving error as : 
Package python conflicts for:
casm-cpp=1.2.0 -> python_abi=3.9[build=*_cp39] -> python=3.9
python=3.6

**Comment by xivh** [comment]
Can you post the output of `pip freeze` and `conda list`? My first guess would be to downgrade numpy, `pip install numpy==1.20.0`.

**Comment by darjaved** [comment]
I sorted this issue now. 
thanks
